spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:algoviz}
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_by.default_null_ordering: last
        format_sql: true
    open-in-view: false
    generate-ddl: true
server:
  port: 8080